---

- name: "configuration prometheus server." 
  hosts: prometheus
  user: "ubuntu"
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: wait for target connection to become reachable/usable.
      # Your code here
      wait_for_connection:
        timeout: 500
    - name: install python for Ansible.
      # Your code here
      become: true
      apt:
        name: python3
        state: present
      changed_when: false

  roles:
    - configure-prometheus-server