global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#general'
    send_resolved: true
    text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
