global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#general'
    send_resolved: true
